enum OrderStatus {
  AGUARDANDO_PAGAMENTO = "AGUARDANDO_PAGAMENTO",
  PAGAMENTO_APROVADO = "PAGAMENTO_APROVADO",
  EM_PREPARO = "EM_PREPARO",
  PRONTO = "PRONTO",
  ENTREGUE = "ENTREGUE",
  CANCELADO = "CANCELADO"
}

export { OrderStatus };